### ISSUE TITLE
Generating OAuth token from headless server

### ISSUE THREAD

**Issue by voxnonecho** [jchrom/trelloR#12]
Implement a method for generating OAuth token from headless server. Something similar to [this](https://support.rstudio.com/hc/en-us/articles/217952868-Generating-OAuth-tokens-from-a-server)

**Comment by jchrom** [comment]
@voxnonecho and @aedobbyn you have probably thought of that, but I am mentioning it anyway in case I won't be able to provide a good solution quickly: Have you tried generating the token on a desktop using the browser and copying it to the server? Having the `.httr-oauth` file in the working directory should allow you to call `trello_get_token` the usual way without having to go through that browser-based authorization.

As for the OOB option, it seems to only be available for OAuth 2.0 via the `oauth2.0_token` function from **httr**. Since Trello is using OAuth 1.0, I am calling `oauth1.0_token` which does not have the `use_oob` argument. Unless Trello adopts OAuth 2.0, the route suggested on RStudio support page is not an option.

I will try and explore other options though.

**Comment by aedobbyn** [comment]
@jchrom I did try just copying the `.httr-oath` file to the server but got the familiar prompt to authenticate in the browser. Not sure whether that was related to `googlesheets` or `trelloR` not making it into the `.httr-oath` file. Will keep you updated of any developments!

**Comment by jchrom** [comment]
googlesheets... the plot thickens! So how exactly are you using it? @aedobbyn

**Comment by aedobbyn** [comment]
@jchrom sorry for the slow reply, haven't touched this in a while. What I'm going is grabbing Trello tickets, munging them, and outputting some summaries to a googlesheet on a cron job. I think it was googlesheets that was giving me an issue. 

Question, though: I'll need to authenticate in the browser and replace that .httr-oauth file every month or so for the token to stay current, right?

**Comment by jchrom** [comment]
Hi @aedobbyn I have added support for "never" expiring tokens (so they remain valid until you disable them directly from Trello). This is not on CRAN yet (and won't be for a while) but you can use the [latest release (0.3)](https://github.com/jchrom/trelloR/releases) from GitHub.

I haven't gotten anywhere on browser-less token creation yet, sorry about that.

**Comment by aedobbyn** [comment]
@jchrom amazing! Thanks a bunch. I'll let you know if I run into any issues!

**Comment by jchrom** [comment]
After talking to someone who knows more about how the web works, I think this should not be implemented, as producing the token on the server would require all sorts of hard-to-secure things like storing people's passwords.

Given the token can be produced locally with unlimited expiration and then copied over where needed, it should not even be a big issue (though a month-long expiration is probably more secure).

Closing the issue.
