### ISSUE TITLE
Internal Server Error (HTTP 500) when authenticating 

### ISSUE THREAD

**Issue by deneara** [jchrom/trelloR#26]
Hi jchrom, 

I am new to R. I am trying to access my private boards but I keep getting the following error:

> my_token = trello_get_token("Trello_key", "Trello_token")
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Internal Server Error (HTTP 500).

I followed the [API instructions](https://developers.trello.com/docs/api-introduction) from Trello and created both a key and token, which were copied correctly into the code above. 

Any suggestions would be greatly appreciated!

Thanks,
Deneara

**Comment by deneara** [comment]
Nevermind, I figured it out. I was using the wrong secret. For others with this issue, the secret is further down on the key page.

**Comment by jchrom** [comment]
Hi @deneara 

good job, I was just replying to you but you figured it out!

As a side note, please use the GitHub version of trelloR, as the CRAN one is quite dated. I really want to update the CRAN version but I keep getting distracted.

I hope the package will be useful to you! Let me know if you encounter issues or want to suggest improvements.

Cheers,
Jakub

**Comment by aidandmorrison** [comment]
Thanks @deneara, I was stuck on the same issue, just didn't scroll down to the secret!  All humming now...  This is a cool package @jchrom, very excited to use it some more.

**Comment by anarguez** [comment]
Hi,

I have the same problem here, but it's not because I'm using the wrong secret key. I got the api key and the secret one from Trello's website and this is what comes up...

**token = get_token(api_key, api_secret)
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Internal Server Error (HTTP 500)**
 
Also, the board I want to have access to is not private, it's visible for team members, does it make a difference?

Thank you very much,
Regards,
Ana.

**Comment by jchrom** [comment]
Hi @anarguez ,

thanks for notifying me about this issue!

Error 500 suggests something went wrong on the Trello side, i.e. the problem might be not caused by whatever comes from you (client) but Trello (server). I'd like to try and replicate the issue anyway though, so I will set up a team board (which is also kind of "private" - in that requires authentication to view, but maybe I should update my API docs to be less confusing).

Just to make sure: Are you using trelloR from CRAN, or from GitHub? Please use the one from GitHub, as the CRAN one is really dated and I am not thrilled at the prospect of debugging it.

**Comment by anarguez** [comment]
Hi @jchrom , 

Thanks for the quick reply. I made it work. I don't know exactly how, because I tried a lot of things... The last thing I tried was requesting a token from Trello website, the one they offer to start trying the API. And when I did, a window appeared asking for permission for the app to access my Trello boards. I allowed it, and when I tried again the function "get_token()", it worked... 

I was indeed using trelloR from GitHub. 
Anyway, thank you for sharing this amazing package that makes it way easier to extract data from Trello API. 

Regards,
Ana.
